CREATE TABLE IF NOT EXISTS sneaker
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model        VARCHAR(100) NOT NULL,
    release_date DATE         NOT NULL,
    brand        VARCHAR(50)  NOT NULL,
    price        DECIMAL(10,2) NOT NULL,
    size         INTEGER      NOT NULL
);

INSERT INTO sneaker (model, release_date, brand, price, size)
VALUES ('Air Max 90', '2023-01-15', 'Nike', 12999.99, 42),
       ('Superstar', '2023-05-23', 'Adidas', 8999.99, 43),
       ('RS-X', '2023-08-30', 'Puma', 9999.99, 41);
